# Generated by Django 3.2 on 2021-04-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayedAt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.TextField(max_length=250)),
                ('show', models.CharField(choices=[('A', 'Acoustic'), ('R', 'Rock'), ('J', 'Jazz')], default='A', max_length=1)),
                ('pedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pedal')),
            ],
        ),
    ]
