# Generated by Django 3.2 on 2021-04-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_playedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='playedat',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='playedat',
            name='date',
            field=models.DateField(verbose_name='show date'),
        ),
    ]
