# Generated by Django 3.2 on 2021-04-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210421_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedal',
            name='instruments',
            field=models.ManyToManyField(to='main_app.Instrument'),
        ),
    ]
