# Generated by Django 3.2 on 2021-04-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pedal_instruments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('pedal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pedal')),
            ],
        ),
    ]
